<?php
/**
 * Tests for dominant-color module.
 *
 * @since 1.2.0
 *
 * @package performance-lab
 * @group   dominant-color
 */

use PerformanceLab\Tests\TestCase\DominantColorTestCase;

class Dominant_Color_Image_Editor_Imageick_Test extends DominantColorTestCase {
	public function set_up() {
		parent::set_up(); // TODO: Change the autogenerated stub.

		add_filter(
			'wp_image_editors',
			static function () {
				return array( 'Dominant_Color_Image_Editor_Imagick' );
			},
			100
		);
	}

	/**
	 * Test if the function returns the correct color.
	 *
	 * @dataProvider provider_get_dominant_color
	 *
	 * @covers       Dominant_Color_Image_Editor_GD::get_dominant_color
	 */
	public function test_get_dominant_color( $image_path, $expected_color, $expected_transparency ) {

		$attachment_id = $this->factory->attachment->create_upload_object( $image_path );
		wp_maybe_generate_attachment_metadata( get_post( $attachment_id ) );

		$dominant_color_data = _dominant_color_get_dominant_color_data( $attachment_id );

		$this->assertContains( $dominant_color_data['dominant_color'], $expected_color );
		if ( strpos( $image_path, '.gif' ) ) {
			$expected_transparency = true; // all gif have alpha.
		}
		$this->assertSame( $dominant_color_data['has_transparency'], $expected_transparency );
	}

	/**
	 * Test if the function returns the correct color.
	 *
	 * @dataProvider provider_get_dominant_color_invalid_images
	 *
	 * @covers       Dominant_Color_Image_Editor_GD::get_dominant_color
	 */
	public function test_get_dominant_color_invalid( $image_path, $expected_color, $expected_transparency ) {

		$attachment_id = $this->factory->attachment->create_upload_object( $image_path );
		wp_maybe_generate_attachment_metadata( get_post( $attachment_id ) );

		$dominant_color_data = _dominant_color_get_dominant_color_data( $attachment_id );

		$this->assertContains( $dominant_color_data['dominant_color'], $expected_color );
		$this->assertSame( $dominant_color_data['has_transparency'], $expected_transparency );
	}

	/**
	 * Test svg file
	 *
	 * @covers Dominant_Color_Image_Editor_GD::get_dominant_color
	 */
	public function test_get_dominant_color_svg() {
		$image_path    = TESTS_PLUGIN_DIR . '/tests/testdata/modules/images/dominant-color/video-play.svg';
		$attachment_id = $this->factory->attachment->create_upload_object( $image_path );
		wp_maybe_generate_attachment_metadata( get_post( $attachment_id ) );

		$dominant_color_data = _dominant_color_get_dominant_color_data( $attachment_id );

		$this->assertInstanceOf( 'WP_Error', $dominant_color_data );
	}

	/**
	 * Test pdf file
	 *
	 * @covers Dominant_Color_Image_Editor_GD::get_dominant_color
	 */
	public function test_get_dominant_color_pdf() {
		$image_path    = TESTS_PLUGIN_DIR . '/tests/testdata/modules/images/dominant-color/wordpress-gsoc-flyer.pdf';
		$attachment_id = $this->factory->attachment->create_upload_object( $image_path );
		wp_maybe_generate_attachment_metadata( get_post( $attachment_id ) );

		$dominant_color_data = _dominant_color_get_dominant_color_data( $attachment_id );

		$this->assertStringContainsString( 'e8e8e8', $dominant_color_data['dominant_color'] );
		$this->assertFalse( $dominant_color_data['has_transparency'] );
	}
}
