version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - 'no milestone'
      - '[Type] Enhancement'
      - 'github_actions'
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - 'no milestone'
      - '[Type] Enhancement'
      - 'javascript'
    cooldown:
      default-days: 7
    groups:
      wordpress-packages:
        patterns:
          - '@wordpress/*'
    ignore:
      # This is to remain compatible with the node in ../.nvmrc and <https://github.com/WordPress/gutenberg/blob/trunk/.nvmrc>.
      - dependency-name: "@types/node"
        versions: [">= 21"]

  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - 'no milestone'
      - '[Type] Enhancement'
      - 'php'
    cooldown:
      default-days: 7
    groups:
      phpstan-packages:
        patterns:
          - 'phpstan/*'
