codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 80%
        base: auto
        informational: true
    patch:
      default:
        threshold: 80%
        informational: true