<?php
/**
 * Tests for webp-uploads module.
 *
 * @package performance-lab
 * @group   webp-uploads
 */

class get_dominant_color_Imagick_Tests extends WP_UnitTestCase {

	function set_up() {
		parent::set_up(); // TODO: Change the autogenerated stub.

		add_filter( 'wp_image_editors', static function () {
			return array( 'WP_Image_Editor_Imagick' );
		} );
	}

	/**
	 * Test if the function returns the correct color.
	 * @dataProvider provider_get_dominant_color
	 *
	 * @covers ::get_dominant_color_GD
	 */
	function test_get_dominant_color( $image_path, $expected_color ) {
		$attachment_id = $this->factory->attachment->create_upload_object( $image_path );

		$this->assertEquals( $expected_color, ( new WP_Dominant_Color() )->get_dominant_color( $attachment_id ) );
	}

	/**
	 * Data provider for test_get_dominant_color_GD.
	 *
	 * @return array
	 */
	function provider_get_dominant_color() {
		return array(

			'jpg'  => array(
				'image_path'     => TESTS_PLUGIN_DIR . '/tests/testdata/modules/images/leafs.jpg',
				'expected_color' => '293e24',
			),
			'png'  => array(
				'image_path'     => TESTS_PLUGIN_DIR . '/tests/testdata/modules/images/dice.png',
				'expected_color' => '293e24',
			),
			'gif'  => array(
				'image_path'     => TESTS_PLUGIN_DIR . '/tests/testdata/modules/images/earth.gif',
				'expected_color' => '293e24',
			),
			'webp' => array(
				'image_path'     => TESTS_PLUGIN_DIR . '/tests/testdata/modules/images/balloons.webp',
				'expected_color' => 'c2bdbc',
			),
		);
	}

	/**
	 * Test if the function returns the correct color.
	 * @dataProvider provider_get_has_transparency
	 *
	 * @covers ::get_dominant_color_GD
	 */
	function test_get_has_transparency( $image_path, $expected_transparency ) {
		$attachment_id = $this->factory->attachment->create_upload_object( $image_path );

		$this->assertEquals( $expected_transparency, ( new WP_Dominant_Color() )->get_has_transparency( $attachment_id ) );
	}

	/**
	 * Data provider for test_get_dominant_color_GD.
	 *
	 * @return array
	 */
	function provider_get_has_transparency() {
		return array(

			'jpg_no_tran'  => array(
				'image_path'            => TESTS_PLUGIN_DIR . '/tests/testdata/modules/images/leafs.jpg',
				'expected_transparency' => false,
			),
			'jpg_has_tran' => array(
				'image_path'            => TESTS_PLUGIN_DIR . '/tests/testdata/modules/images/dice.png',
				'expected_transparency' => true,
			),
			'webp_no_tran' => array(
				'image_path'            => TESTS_PLUGIN_DIR . '/tests/testdata/modules/images/balloons.webp',
				'expected_transparency' => false,
			),
		);
	}
}
