name: JS Code Linting

on:
  push:
    branches:
      - trunk
      - 'release/**'
    # Only run if JS/JSON/Lint/NVM files changed.
    paths:
      - '.github/workflows/js-lint.yml'
      - '**.js'
      - '**.json'
      - '.eslint*'
      - '.nvmrc'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
  pull_request:
    # Only run if JS/JSON/Lint/NVM files changed.
    paths:
      - '.github/workflows/js-lint.yml'
      - '**.js'
      - '**.json'
      - '.eslint*'
      - '.nvmrc'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  js-lint:
    name: JS Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Node.js (via .nvmrc)
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: npm install
        run: |
          npm ci
          npm ci --prefix plugins/optimization-detective/priming-cli
      - name: JS Lint
        run: npm run lint-js
      - name: TypeScript compile
        run: npm run tsc
