name: JS Code Linting

on:
  push:
    branches:
      - trunk
      - 'release/**'
    # Only run if JS/JSON/Lint/NVM files changed.
    paths:
      - '.github/workflows/js-lint.yml'
      - '**.js'
      - '**.json'
      - '.eslint*'
      - '.nvmrc'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
  pull_request:
    # Only run if JS/JSON/Lint/NVM files changed.
    paths:
      - '.github/workflows/js-lint.yml'
      - '**.js'
      - '**.json'
      - '.eslint*'
      - '.nvmrc'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  js-lint:
    name: JS Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: styfle/cancel-workflow-action@3155a141048f8f89c06b4cdae32e7853e97536bc # 0.13.0
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js (via .nvmrc)
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: npm install
        run: npm ci
      - name: JS Lint
        run: npm run lint-js
      - name: JSON Schema Validation
        run: npm run lint-json
      - name: TypeScript compile
        run: npm run tsc
