name: Spell Check

on: [pull_request]

# Cancel previous workflow run groups that have not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  spell-checker:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read # Required to clone the repo.
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Search for misspellings
        uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0
        with:
          config: ./.github/typos.toml
