name: Spell Check

on: [pull_request]

jobs:
  spell-checker:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Search for misspellings
        uses: crate-ci/typos@626c4bedb751ce0b7f03262ca97ddda9a076ae1c # master
        with:
          config: ./.github/typos.toml
