name: Spell Check

on: [pull_request]

jobs:
  spell-checker:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Search for misspellings
        uses: crate-ci/typos@master
        with:
          config: ./.github/typos.toml
