name: Spell Check

on: [pull_request]

jobs:
  spell-checker:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v5
      - name: Search for misspellings
        uses: crate-ci/typos@626c4bedb751ce0b7f03262ca97ddda9a076ae1c # master
        with:
          config: ./.github/typos.toml
